# Generated by Django 6.0 on 2026-02-12 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено пациентом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to=settings.AUTH_USER_MODEL, verbose_name='👨\u200d⚕️ Врач')),
                ('patient', models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to=settings.AUTH_USER_MODEL, verbose_name='🧑 Пациент')),
            ],
            options={
                'verbose_name': 'Связь врач-пациент',
                'verbose_name_plural': 'Связи врач-пациент',
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
