# Generated by Django 6.0 on 2026-02-14 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorpatientrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_doctor': False}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to=settings.AUTH_USER_MODEL, verbose_name='🧑 Пациент'),
        ),
    ]
