# Generated by Django 6.0 on 2026-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctorpatientrelation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является врачом', verbose_name='Врач'),
        ),
        migrations.AddIndex(
            model_name='doctorpatientrelation',
            index=models.Index(fields=['doctor', 'patient'], name='accounts_do_doctor__0d51e4_idx'),
        ),
    ]
