# Generated by Django 6.0 on 2026-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lifestyle',
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_xe_norm',
            field=models.PositiveIntegerField(default=18, help_text='Укажите вашу дневную норму хлебных единиц', verbose_name='Дневная норма ХЕ'),
        ),
    ]
