# Generated by Django 6.0 on 2025-12-28 21:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Приём пищи', 'verbose_name_plural': 'Приёмы пищи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='📖 Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/', verbose_name='🖼 Обложка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, verbose_name='🧾 Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='📰 Заголовок'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='🍬 Углеводы (г)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='🍎 Продукт'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='👤 Пользователь'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='xe',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='🍞 Хлебные единицы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs_per_100g',
            field=models.FloatField(verbose_name='🥖 Углеводы (г) на 100 г продукта'),
        ),
    ]
