# Generated by Django 6.0 on 2026-01-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='📅 Дата')),
                ('comment', models.TextField(blank=True, verbose_name='📝 Комментарий / самочувствие')),
                ('mood', models.PositiveSmallIntegerField(default=3, verbose_name='🙂 Самочувствие (1–5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='👤 Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий дня',
                'verbose_name_plural': 'Комментарии дней',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
