# Generated by Django 6.0 on 2026-01-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_daycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayComment',
        ),
    ]
